<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<? $this->area = $this->salon->getArea(); ?>
<?=$this->ShowUrlBack($this->salon);?>
<div class="singleSalonBox">
    <?=$this->ShowSalonHeader($this->salon);?>
    <?=$this->ShowSalonMenu($this->salon, 'about');?>
</div>
<div class="descText">
    <article>
        <p></p>
        <?=$this->contentPage['content']->getFieldText();?>
        <p></p>
    </article>
</div>