<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<?=$this->ShowSubscribe();?>
<div class="breadcrumbs">
    <span>
        <a href="http://<? echo SITE_NAME ?>"><?=Kernel_Block::getText('Салоны эротического массажа', $this->blocks);?></a>
    </span>
    <span>
        <a href="<?=Kernel_City::getUrlForLink(Kernel_City::findCityFromUrl())?>">Киев</a>
    </span>
    <span>
        <a href="<?=$this->url();?>"><?=$this->areaContent['contentName']->getFieldText();?></a>
    </span>
</div>
<div id="list_block">
    <?php echo $this->partial('block/list.phtml', array (
                                                        'salons' => $this->salons
                                                  )) ?>
</div>

<?=$this->ShowSubscribe();?>
<div class="descText">
    <article>
        <?=$this->text;?>
    </article>
</div>