<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<?=$this->ShowSubscribe();?>
<div class="breadcrumbs">
    <span>
        <a href="http://<? echo SITE_NAME ?>"><?=Kernel_Block::getText('Салоны эротического массажа', $this->blocks);?></a>
    </span>
    <span>
        <a href="<?=Kernel_City::getUrlForLink(Kernel_City::findCityFromUrl())?>">Киев</a>
    </span>
    <span>
        <a href="<?=$this->url();?>"><?=$this->areaContent['contentName']->getFieldText();?></a>
    </span>
</div>
<?php foreach ($this->salons->data as $k=>$salon): ?>
    <? $content = $salon->getContent()->getFields();?>
    <div class="salonItem">
        <div class="newSalonLabel"></div>
        <div class="salonInfo">
            <a href="<?=Kernel_City::getUrlForLink($salon->getCity())?><?=$salon->getRoute()->getUrl();?>" class="salonLogo">
                <img src="<?=$salon->getPhoto1()->getPath('120:120');?>" alt="">
                <h3><?=$content['name']->getFieldText();?></h3>
            </a>
            <div class="clear"></div>
            <a class="location" href="<?=$this->url();?>"><?=$this->areaContent['contentName']->getFieldText();?></a>
            <div class="commentValueBox">
                <span class="commentIcon"></span> – <a href="<?=Kernel_City::getUrlForLink($salon->getCity())?><?=$this->url(array('url_key'=>$salon->getUrlKey()), 'default-salon-review');?>"><?=count($salon->getComments())?> отзывов</a>
            </div>
            <em><?=Kernel_Block::getText('положительных', $this->blocks);?> – <?=count($salon->getGoodComments())?></em>
            <br>
            <em><?=Kernel_Block::getText('отрицательных', $this->blocks);?> – <?=count($salon->getBadComments())?></em>
            <div class="clear"></div>
        </div>
        <div class="salonModelBox">
            <? foreach ($salon->getGirls() as $k=>$girl): ?>
                <? $contentGirl = $girl->getContent()->getFields();?>
                <? $photo = $girl->getGallery()->getFirstPhoto(); ?>
                <a href="#" class="salonModelItem">
                    <img src="<?=$photo->getPath('240:240');?>" alt="">
                    <h4><?=$contentGirl['contentName']->getFieldText();?></h4>
                </a>
            <? endforeach; ?>
        </div>
        <div class="clear"></div>
    </div>
    <? if ($k == 1): ?>
        <div class="content-info">
            <a href="#">
                <img src="/static/default/images/content/contentInfo.png" alt="">
            </a>
        </div>
    <? endif; ?>
<? endforeach; ?>
<?=$this->paginationControl($this->salons->paginator, 'Sliding', 'block/paginator.phtml')?>
<?=$this->ShowSubscribe();?>
<div class="descText">
    <article>
<!--        <p>Все салоны эротического массажа в каталоге My-Relax <br> Каталог my-relax.net - самый полный каталог-->
<!--            действующих салонов эротического массажа в Украине. На сегодняшний день посещение салона эротического-->
<!--            массажа - это достаточно популярный способ отдыха и развлечений. Благодаря своей популярности среди жителей-->
<!--            Украины и всего мира, эротический массаж представлен в самых разнообразных формах.</p>-->
<!---->
<!--        <p>В нашем каталоге представлено около 50 салонов эротического массажа крупных городов Украины: Киев,-->
<!--            Днепропетровск, Одесса, Донецк, Харьков, Винница. Для удобного выбора салона на сайте представлены описание-->
<!--            и преимущества салонов, координаты, а также их месторасположение на карте. Также Вы можете выбрать салон в-->
<!--            зависимости от видов эротического массажа и дополнительных услуг, которые предлагают салоны, и ценовой-->
<!--            политики. Также Вашему вниманию предлагаем фотографии и параметры девушек, реальные отзывы о массажистках.-->
<!--            Выбирайте лучший салон!</p>-->
<!---->
<!--        <p>Наиболее распространенные предложения салонов: классический эротический массаж (массирование и расслабление-->
<!--            всего тела от макушки </p>-->
    </article>
</div>