<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<?=$this->ShowSubscribe();?>
<? $city = Kernel_City::findCityFromUrl();?>
<? $cityConten = $city->getContent()->getFields();?>
<? if($this->salons->paginator->count() < 2): ?>
    <script>
        page = 0;
    </script>
<? endif; ?>
<div class="breadcrumbs">
    <span>
        <a href="http://<? echo SITE_NAME ?>"><?=Kernel_Block::getText('Салоны эротического массажа', $this->blocks);?></a>
    </span>
    <? if (!isset($this->regionContent)): ?>
        <span>
            <a href="<?=Kernel_City::getUrlForLink($city)?>"><?=$cityConten['contentName']->getFieldText();?></a>
        </span>
        <span>
            <span><?=$this->areaContent['contentName']->getFieldText();?></span>
        </span>
    <? else: ?>
        <span>
            <a href="<?=Kernel_City::getUrlForLink($city)?>"><?=$cityConten['contentName']->getFieldText();?></a>
        </span>
        <span>
            <a href="<?=Kernel_City::getUrlForLink($city)?>/<?=$this->area->getUrl();?>"><?=$this->areaContent['contentName']->getFieldText();?></a>
        </span>
        <span>
            <span><?=$this->regionContent['contentName']->getFieldText();?></span>
        </span>
    <? endif ?>
</div>
<div id="list_block">
    <?php echo $this->partial('block/list.phtml', array (
                                                        'salons' => $this->salons,
                                                        'siteSetings' => $this->siteSetings
                                                  )) ?>
</div>

<?=$this->ShowSubscribe();?>
<div class="descText">
    <article">
    <div class="map-wrap" id="map-wrap"></div>
    </article>
</div>
<div class="descText">
    <article>
        <?=$this->text;?>
    </article>
</div>
<script src="http://maps.googleapis.com/maps/api/js?sensor=false&language=ru"></script>
<script>
    var map;
    var openedWindow = false;
    function setMap()
    {
        var main = $('.salonItem').first();
        var mapOptions = {
            center: new google.maps.LatLng(main.data('lat'), main.data('lng')),
            zoom:13,
            mapTypeId:google.maps.MapTypeId.ROADMAP,
            scrollwheel:false
        };
        var map = new google.maps.Map(document.getElementById("map-wrap"),
            mapOptions)

        $('.salonItem').each(function(index){

            var name = $(this).find('h3').html();

            var marker = new google.maps.Marker({
                map:map,
                position: new google.maps.LatLng($(this).data('lat'), $(this).data('lng'))
            });

            var infowindow = new google.maps.InfoWindow(
                {
                    content: '<div style="padding: 15px;">'+
                        '<img src="'+$(this).data('img')+'" width="80" height="80">'+
                        '<br/><b><a style="color:blue;" href="'+$(this).data('url')+'">'+name+'</a></b></div>'
                });

            google.maps.event.addListener(marker, 'click', function () {
                if (openedWindow)
                    openedWindow.close();
                openedWindow = infowindow;
                infowindow.open(map, marker);
                map.setCenter(marker.getPosition());
            });

        });

        return false;
    }

    $(document).ready(function(){
        setMap();
        $(window).scroll(function() {

            var currentPosition = $(window).scrollTop() + $(window).height();
            var positionToGet = $(document).height() - (600 + $('.descText > article').height());
            if( currentPosition >= positionToGet ) {
                getAjaxPage();
            }
        });
    });
</script>