<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<?//=$this->product->getPhoto1()->getPath('400', true)?>
<div class="breadcrumbs">
    <span class="backToList">
        <a href="#">Назад к списку</a>
    </span>
</div>
<div class="singleSalonBox">
    <?=$this->ShowSalonHeader($this->salon);?>
    <?=$this->ShowSalonMenu($this->salon, 'girls');?>
    <div class="mobileMenu">
        <ul>
            <li><a class="current" href="#">Девушки</a></li>
            <li><a href="#">Цены</a></li>
            <li><a href="#">Отзывы</a></li>
            <li><a href="#">Карта</a></li>
        </ul>
    </div>
    <div class="salonContent">
        <div class="salonSidebar" style="background: url(images/content/salonCover2.png) no-repeat center center;">
        </div>
        <div class="salonContentRight">
            <h3>Девушки салона</h3>
            <div class="singleSalonModelItem">
                <p><span>Сабина</span>, 23 год</p>
                <div id="carousel-1" class="salonModelCarouselWrap">
                    <img src="images/content/salonModel11.png" alt="">
                    <img src="images/content/salonModel12.png" alt="">
                    <img src="images/content/salonModel13.png" alt="">
                    <img src="images/content/salonModel14.png" alt="">
                    <img src="images/content/salonModel15.png" alt="">
                    <img src="images/content/salonModel16.png" alt="">
                </div>
                <a id="prev-model-1" class="carouselNav prev" href="#"></a>
                <a id="next-model-1" class="carouselNav next" href="#"></a>
                <div class="loaderBox"></div>
            </div>
            <div class="singleSalonModelItem">
                <p><span>Айрин</span>, 20 лет</p>
                <div id="carousel-2" class="salonModelCarouselWrap">
                    <img src="images/content/salonModel14.png" alt="">
                    <img src="images/content/salonModel15.png" alt="">
                    <img src="images/content/salonModel16.png" alt="">
                    <img src="images/content/salonModel11.png" alt="">
                    <img src="images/content/salonModel12.png" alt="">
                    <img src="images/content/salonModel13.png" alt="">
                </div>
                <a id="prev-model-2" class="carouselNav prev" href="#"></a>
                <a id="next-model-2" class="carouselNav next" href="#"></a>
                <div class="loaderBox"></div>
            </div>
            <div class="singleSalonModelItem">
                <p><span>Барбара</span>, 23 года</p>
                <div id="carousel-3" class="salonModelCarouselWrap">
                    <img src="images/content/salonModel13.png" alt="">
                    <img src="images/content/salonModel14.png" alt="">
                    <img src="images/content/salonModel15.png" alt="">
                    <img src="images/content/salonModel16.png" alt="">
                    <img src="images/content/salonModel11.png" alt="">
                    <img src="images/content/salonModel12.png" alt="">
                </div>
                <a id="prev-model-3" class="carouselNav prev" href="#"></a>
                <a id="next-model-3" class="carouselNav next" href="#"></a>
                <div class="loaderBox"></div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="salonFooter" style="background: url(images/content/salonCover3.png) no-repeat center center;"></div>
    <?=$this->ShowSalonMenu($this->salon, 'girls');?>
</div>
<div class="descText">
    <article>
        <p></p>
        <?=$this->contentPage['content']->getFieldText();?>
        <p></p>
    </article>
</div>