<?= $this->partial('blocks/menus/top.phtml'); ?>
<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<script src="/static/admin/js/fileuploader.js" type="text/javascript"></script>
<link type="text/css" title="stylesheet" href="/static/admin/css/fileuploader.css" rel="stylesheet"/>
<script>
    function showAreas(e)
    {
        var cityId = $(e).val();

        $('.cities').hide();
        $('.city_'+cityId).show();
    }


    function initUploaderWall(options,idPhoto){
        
        initComplete = function(id, fileName, responseJSON) {
            var data = responseJSON;
            
            if (data.status == false) {
               ShowPopUp('Can not upload image now');
            } else {
                $('#previewImage'+idPhoto).removeClass('hide').attr('href', decodeURIComponent((data.path + '').replace(/&amp;/g, '&')) + '&t=' + new Date().getTime());
                $('#idPhoto'+idPhoto).val(data.idPhoto);
            }
        }

        new qq.FileUploader({
            element: document.getElementById(options.upload_button_id),
            action: options.action, 
            debug: true,
            button_label: options.button_label,
            onComplete: initComplete,
            messages: options.messages,
            showMessage: function(message) {
                alert(message);
            },
            onProgress: function(id, fileName, loaded, total){
                
            }
        }); 

        return false;
    }

     $(document).ready(function(){
        initUploaderWall({
            'upload_button_id':'file_uploader1',
            'action': '<?=$this->url(array('idPhoto'=>$this->idPhoto1),'admin-photo-upload')?>',
            'button_label': 'Загрузить'
        },1);
         initUploaderWall({
             'upload_button_id':'file_uploader2',
             'action': '<?=$this->url(array('idPhoto'=>$this->idPhoto2),'admin-photo-upload')?>',
             'button_label': 'Загрузить'
         },2);
         initUploaderWall({
             'upload_button_id':'file_uploader3',
             'action': '<?=$this->url(array('idPhoto'=>$this->idPhoto3),'admin-photo-upload')?>',
             'button_label': 'Загрузить'
         },3);
         initUploaderWall({
             'upload_button_id':'file_uploader4',
             'action': '<?=$this->url(array('idPhoto'=>$this->idPhoto4),'admin-photo-upload')?>',
             'button_label': 'Загрузить'
         },4);
    });
</script>
<?
if( isset($this->photo1) )
    $photoPath1 = trim($this->photo1->getPhotoPath());
else 
    $photoPath1 = '';
?>
<?
if( isset($this->photo2) )
    $photoPath2 = trim($this->photo2->getPhotoPath());
else 
    $photoPath2 = '';
?>
<?
if( isset($this->photo3) )
    $photoPath3 = trim($this->photo3->getPhotoPath());
else 
    $photoPath3 = '';
?>
<?
if( isset($this->photo4) )
    $photoPath4 = trim($this->photo4->getPhotoPath());
else 
    $photoPath4 = '';
?>
<form action="<?= $this->url() ?>" method="post" id="PageForm"> 
    <table class="zebra edit">
        <tr class="grey">
            <td width="193" class="first">URL:</td>
            <td>
                <input name="realName" type="text" class="field" style="background-color: #F2F2F2; width:10px;" disabled="disabled" value="/" />
                <input name="url" style="width:255px" type="text" class="field" value="<?= (isset($_POST['url'])) ? $_POST['url'] : '' ?>" disabled="disabled" />
                <input name="realNamehtml" type="text" class="field" style="background-color: #F2F2F2; width:30px;" disabled="disabled" value=".html" />
            </td>
        </tr>
        <tr class="">
            <td width="193" class="first">Город:</td>
            <td>
                <select name="city_id" onchange="showAreas(this);">
                    <option value="0">Все города</option>
                <?php foreach( $this->cities as $city ):?>
                    <? $cityContent = $city->getContent()->getFields();?>
                        <option value="<?=$city->getId();?>"
                            <? if (isset($_POST['city_id']) && $_POST['city_id'] == $city->getId()): ?>
                                selected="selected"
                            <? endif;?>
                            ><?=$cityContent['contentName']->getFieldText();?></option>
                <?php endforeach; ?>
                </select>
            </td>
        </tr>
        <?php foreach( $this->cities as $city ):?>
            <tr class="hide cities city_<?=$city->getId();?>"
                <? if (isset($_POST['city_id']) && $_POST['city_id'] == $city->getId()): ?>
                    style="display: table-row;"
                <? endif;?>
                >
                <td width="193" class="first">Район:</td>
                <td>
                    <select name="area_id[<?=$city->getId(); ?>]">
                    <?php foreach( $this->areas as $area ):?>
                        <? if ($area->getCityId() != $city->getId()) continue;?>
                        <? $areaContent = $area->getContent()->getFields();?>
                        <option value="<?=$area->getId();?>"
                            <? if (isset($_POST['area_id']) && $_POST['area_id'] == $area->getId()): ?>
                                selected="selected"
                            <? endif;?>
                            ><?=$areaContent['contentName']->getFieldText();?></option>
                    <?php endforeach; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        <tr class="">
            <td width="193" class="first">Логоти
                <a href="<?if ($this->idPhoto1 === 0 || empty($photoPath1) ): ?>/static/admin/images/nobg.png<? else: echo Application_Model_Kernel_Photo::getById($this->idPhoto1)->getPath('210:130'); endif ?>" target="_blank" id="previewImage1" class="preview <? if ($this->idPhoto1 === 0 || empty($photoPath1) ): ?>hide<? endif ?>" title="">
                    <img src="/static/admin/images/picture.png" alt="">
                </a>
            </td>
            <td>
                <div id="file_uploader1"></div>
            </td>
        </tr>
        <tr class="">
            <td width="193" class="first">Баннер Шапка (939:261)
                <a href="<?if ($this->idPhoto2 === 0 || empty($photoPath2) ): ?>/static/admin/images/nobg.png<? else: echo Application_Model_Kernel_Photo::getById($this->idPhoto2)->getPath('210:130'); endif ?>" target="_blank" id="previewImage2" class="preview <? if ($this->idPhoto2 === 0 || empty($photoPath2) ): ?>hide<? endif ?>" title="">
                    <img src="/static/admin/images/picture.png" alt="">
                </a>
            </td>
            <td>
                <div id="file_uploader2"></div>
            </td>
        </tr>
        <tr class="">
            <td width="193" class="first">Баннер Подвал (940:150)
                <a href="<?if ($this->idPhoto3 === 0 || empty($photoPath3) ): ?>/static/admin/images/nobg.png<? else: echo Application_Model_Kernel_Photo::getById($this->idPhoto3)->getPath('210:130'); endif ?>" target="_blank" id="previewImage3" class="preview <? if ($this->idPhoto3 === 0 || empty($photoPath3) ): ?>hide<? endif ?>" title="">
                    <img src="/static/admin/images/picture.png" alt="">
                </a>
            </td>
            <td>
                <div id="file_uploader3"></div>
            </td>
        </tr>
        <tr class="">
            <td width="194" class="first">Баннер Сайдбар (220:1140)
                <a href="<?if ($this->idPhoto4 === 0 || empty($photoPath4) ): ?>/static/admin/images/nobg.png<? else: echo Application_Model_Kernel_Photo::getById($this->idPhoto4)->getPath('210:140'); endif ?>" target="_blank" id="previewImage4" class="preview <? if ($this->idPhoto4 === 0 || empty($photoPath4) ): ?>hide<? endif ?>" title="">
                    <img src="/static/admin/images/picture.png" alt="">
                </a>
            </td>
            <td>
                <div id="file_uploader4"></div>
            </td>
        </tr>
        <tr class="grey">
            <td width="193" class="first">Телефон:</td>
            <td>
                <input name="phone" style="width:255px" type="text" class="field" value="<?= (isset($_POST['phone'])) ? $_POST['phone'] : '' ?>" />
            </td>
        </tr>
        <tr class="grey">
            <td width="193" class="first">Цена звонка:</td>
            <td>
                <input name="call_price" style="width:255px" type="text" class="field" value="<?= (isset($_POST['call_price'])) ? $_POST['call_price'] : '' ?>" />
            </td>
        </tr>
        <tr class="grey">
            <td width="193" class="first">Lat:</td>
            <td>
                <input name="lat" style="width:255px" type="text" class="field" value="<?= (isset($_POST['lat'])) ? $_POST['lat'] : '' ?>" />
            </td>
        </tr>
        <tr class="grey">
            <td width="193" class="first">Lng:</td>
            <td>
                <input name="lng" style="width:255px" type="text" class="field" value="<?= (isset($_POST['lng'])) ? $_POST['lng'] : '' ?>" />
            </td>
        </tr>

    </table>
    <div id="tabs">
		<?php if (sizeof($this->langs) > 1): ?>
			<ul>
				<?php foreach ($this->langs as $lang): ?>
					<li><a href="#<?=$lang->getIsoName()?>"><?=$lang->getFullName()?></a></li>
				<?php endforeach ?>
			</ul>
		<?php endif ?>
		<?php foreach ($this->langs as $lang): ?>
			<div id="<?=$lang->getIsoName()?>"> 
				<table class="zebra edit">
					<tr class="grey">
						<td width="193" class="first">Название:</td>
						<td><input name="content[<?=$lang->getId()?>][name]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['name'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['name']) : ''?>" /></td>
					</tr>
                    <tr class="">
                        <td width="193" class="first">Head:</td>
                        <td><input name="content[<?=$lang->getId()?>][head]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['head'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['head']) : ''?>" /></td>
                    </tr>
					<tr class="">
						<td width="193" class="first">Титл:</td>
						<td><input name="content[<?=$lang->getId()?>][title]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['title'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['title']) : ''?>" /></td>
					</tr>
					<tr class="grey">
						<td width="193" class="first">Дескрипшин:</td>
						<td><input name="content[<?=$lang->getId()?>][description]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['description'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['description']) : ''?>" /></td>
					</tr>
					<tr class="">
						<td width="193" class="first">Кейвордс:</td>
						<td><input name="content[<?=$lang->getId()?>][keywords]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['keywords'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['keywords']) : ''?>" /></td>
					</tr>
					<tr class="grey">
						<td width="193" class="first">Основной текст:</td>
						<td>
							<textarea  id="textareas_<?=$lang->getIsoName()?>" rows='10' class='content' cols='40' name="content[<?=$lang->getId()?>][content]" tabindex='2' ><?=(isset($_POST['content'][$lang->getId()]['content'])) ? $_POST['content'][$lang->getId()]['content'] : ''?></textarea>
						</td>
					</tr>
                    <tr class="">
                        <td width="193" class="first">Акции:</td>
                        <td>
                            <textarea  rows='10' class='content' cols='40' name="content[<?=$lang->getId()?>][discount]" tabindex='2' ><?=(isset($_POST['content'][$lang->getId()]['discount'])) ? $_POST['content'][$lang->getId()]['discount'] : ''?></textarea>
                        </td>
                    </tr>
                    <tr class="grey">
                        <td width="193" class="first">Адресс:</td>
                        <td><input name="content[<?=$lang->getId()?>][adress]" type="text" class="field" value="<?=(isset($_POST['content'][$lang->getId()]['adress'])) ? htmlspecialchars( $_POST['content'][$lang->getId()]['adress']) : ''?>" /></td>
                    </tr>
				</table>
			</div> 
		<?php endforeach ?>
	</div>
    <table>
        <tr class="grey">
            <td colspan="2">
                <div class="m10 centerButton">
                    <input id="idPage" type="hidden" name="idPage" value="<?= $this->idPage ?>" />
                    <input id="idPhoto1" type="hidden" name="idPhoto1" value="<?=$this->idPhoto1?>" />
                    <input id="idPhoto2" type="hidden" name="idPhoto2" value="<?=$this->idPhoto2?>" />
                    <input id="idPhoto3" type="hidden" name="idPhoto3" value="<?=$this->idPhoto3?>" />
                    <input id="idPhoto4" type="hidden" name="idPhoto4" value="<?=$this->idPhoto4?>" />
                    <a href="javascript:SubmitPageFrom();" class="button_blue">Сохранить</a>
                    <a href="<?=$this->url(array('page'=>1),'admin-salon-index') ?>" class="button_grey">Отменить</a>
                </div>
            </td>
        </tr>
    </table>
</form>
<input id="uploadUrl" type="hidden" value="<?=$this->url(array(),'admin-photo-upload')?>"/>