<?php foreach($this->areas as $area): ?>
    <?php $content = $area->getContent()->getFields();?>
    <input class="area_inp area_input_city_<?=$area->getCityId();?>" data-url="<?=$area->getUrl();?>" id="<?=$area->getUrl();?>" type="radio" size="" value="<?=$area->getUrl();?>" name="area" />
    <label style="display: none;" class="area_inp area_in_city_<?=$area->getCityId();?>" for="<?=$area->getUrl();?>"><?=$content['contentName']->getFieldText();?></label>
<?php endforeach; ?>