<div class="breadcrumbs">
    <span>
        <a href="http://<? echo SITE_NAME ?>"><?=Kernel_Block::getText('Салоны эротического массажа', $this->blocks);?></a>
    </span>
    <span>
        <a href="<?=$this->cityUrl?>"><?=$this->cityContent['contentName']->getFieldText();?></a>
    </span>
    <span>
        <a href="<?=$this->cityUrl?>/<?=$this->area->getUrl()?>"><?=$this->areaContent['contentName']->getFieldText();?></a>
    </span>
    <span>
        <span><?=$this->salonContent['name']->getFieldText();?></span>
    </span>
</div>