<?php foreach ($this->salons->data as $k=>$salon): ?>
    <?php echo $this->partial('block/item.phtml', array (
                                                        'salon' => $salon,
                                                        'blocks' => $this->blocks
                                                  )) ?>
    <? if ($k == 1): ?>
        <div class="content-info">
            <a href="<?=$this->siteSetings->getUrl2();?>">
                <img src="<?=$this->siteSetings->getPhoto2()->getPath('940:120')?>" alt="">
            </a>
        </div>
    <? endif; ?>
<? endforeach; ?>
<?//=$this->paginationControl($this->salons->paginator, 'Sliding', 'block/paginator.phtml')?>