<?php if ( $this->pageCount > 1 ): ?>
    <div class="pagination">
        <ul>
            <?php if (isset($this->previous)): ?>
                <li class="prev"><a href="<?= $this->url(array("page" => $this->previous)) ?>" data-page="<?=$this->previous?>"></a></li>
            <?php endif; ?>
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li><a href="<?= $this->url(array("page" => $page)) ?>" data-page="<?=$page?>"><?= $page; ?></a></li>
                <?php else: ?>
                    <li class="current"><?= $page; ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if (isset($this->next)): ?>
                <li class="next"><a href="<?= $this->url(array("page" => $this->next)) ?>" data-page="<?=$this->next?>"></a></li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>