<div class="salonHeader" style="background: url(<?=$this->salon->getPhoto2()->getPath('939:261');?>) no-repeat center center;">
    <div class="salonMetaBox">
        <div class="singleSalonLogo">
            <img src="<?=$this->salon->getPhoto1()->getPath('120:120');?>" alt="">
        </div>
        <h2><?=$this->contentPage['name']->getFieldText();?></h2>
        <div class="clear"></div>
        <a class="location" href="<?=$this->salon->getRoute()->getUrl();?>"><?=$this->contentPage['adress']->getFieldText();?></a>
        <div class="singleSalonCommentsBox">
            <a href="<?=$this->url(array('url_key'=>$this->salon->getUrlKey()), 'default-salon-review');?>">– <?=$this->countAllComments; ?> отзывов</a>
            <em>положительных – <?=$this->countGoodComments; ?></em><br>
            <em>нейтральных – <?=$this->countNormalComments; ?></em><br>
            <em>отрицательных – <?=$this->countBadComments; ?></em>
        </div>
    </div>
    <div class="salonPhone">
        <span data-salon-phone="<?=$this->salon->getPhone()?>"><?=mb_substr($this->salon->getPhone(), 0, 5)?> XX-XX-XXX</span>
        <a href="#">Показать</a>
    </div>
</div>