<div class="salonHeader" style="background: url(images/content/salonCover1.png) no-repeat center center;">
    <div class="salonMetaBox">
        <div class="singleSalonLogo">
            <img src="images/content/singleLogo.png" alt="">
        </div>
        <h2><?=$this->contentPage['name']->getFieldText();?></h2>
        <div class="clear"></div>
        <a class="location" href="#"><?=$this->contentPage['adress']->getFieldText();?></a>
        <div class="singleSalonCommentsBox">
            <a href="#">– 15 отзывов</a>
            <em>положительных – 12</em><br>
            <em>нейтральных – 2</em><br>
            <em>отрицательных – 1</em>
        </div>
    </div>
    <div class="salonPhone">
        <span data-salon-phone="<?=$this->salon->getPhone()?>"><?=mb_substr($this->salon->getPhone(), 0, 5)?> XX-XX-XXX</span>
        <a href="#">Показать</a>
    </div>
</div>