<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<?=$this->ShowSubscribe();?>
<? $city = Kernel_City::findCityFromUrl();?>
<? if ($city): ?>
    <? $cityConten = $city->getContent()->getFields();?>
    <div class="breadcrumbs">
        <span>
            <a href="http://<? echo SITE_NAME ?>"><?=Kernel_Block::getText('Салоны эротического массажа', $this->blocks);?></a>
        </span>
        <span>
            <span><?=$cityConten['contentName']->getFieldText();?></span>
        </span>
    </div>
<? endif; ?>
<div id="list_block">
    <?php echo $this->partial('block/list.phtml', array (
                                                        'salons' => $this->salons
                                                  )) ?>
</div>
<?=$this->ShowSubscribe();?>
<div class="descText">
    <article>
        <?php echo $this->text ?>
    </article>
</div>
<script>
    $(document).ready(function(){
        /* Используйте вариант $('#more').click(function() для того, чтобы дать пользователю возможность управлять процессом, кликая по кнопке "Дальше" под блоком статей (см. файл index.php) */
        $(window).scroll(function() {
            /* Если высота окна + высота прокрутки больше или равны высоте всего документа и ajax-запрос в настоящий момент не выполняется, то запускаем ajax-запрос */
            if($(window).scrollTop() + $(window).height() >= $(document).height() - 200) {
                getAjaxPage();
            }
        });
    });
</script>