<?= $this->partial('blocks/menus/top.phtml'); ?>
<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<form action="" method="POST">
    <table class="zebra edit">
        <tr class="grey">
            <td width="193" class="first">НикНейм:</td>
            <td>
                <input type="text" name="name" value="<?php echo $this->comment->getCommentNick();?>"/>
            </td>
        </tr>
        <tr class="">
            <td width="193" class="first">Оценка:</td>
            <td>
                <?php echo $this->comment->getCommentTypeText();?>
            </td>
        </tr>
        <tr class="grey">
            <td width="193" class="first">Текст:</td>
            <td>
                <textarea name="text_comment"><?php echo $this->comment->getCommentText();?></textarea>
            </td>
        </tr>
        <tr class="">
            <td width="193" class="first">Дата:</td>
            <td><?php echo Application_Model_Kernel_Date_Manager::formatDate($this->comment->getCommentDate(), Application_Model_Kernel_Date_Manager::TYPE_USER_VIEW)?></td>
        </tr>
        <tr class="grey">
            <td width="193" class="first">Статус:</td>
            <td>
                <select name="status">
                    <option value="0"
                        <? if($this->comment->getCommentStatus() == 0): ?>selected="selected" <? endif; ?>
                        >Добавлен</option>
                    <option value="1"
                            <? if($this->comment->getCommentStatus() == 1): ?>selected="selected" <? endif; ?>
                        >Одобрен</option>
                </select>
            </td>
        </tr>
        <tr class="">
            <td width="193" class="first">Ответ Администрации:</td>
            <td>
                <textarea name="text"><?php echo $this->comment->getCommentAdminText();?></textarea>
            </td>
        </tr>
        <tr class="grey">
            <td width="193" class="first"></td>
            <td>
                <input type="submit" value="Сохранить"/>
            </td>
        </tr>
    </table>
</form>