<? if (isset($_GET['DBG']) || in_array(@$_SERVER['REMOTE_ADDR'], array('127.0.0.1', 'fe80::1', '::1'))): ?>
<html>
	<head>
		<title>Application error</title>
		<?=$this->headMeta()?>
	</head>
  	<body>
		<h2><?php echo $this->message ?></h2>
  		<?php if (isset($this->exception)): ?>
	  		<h3>Exception information:</h3>
	  		<p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>

	  		<h3>Stack trace:</h3>
	  		<pre><?php echo $this->exception->getTraceAsString() ?></pre>

	  		<h3>Request Parameters:</h3>
	  		<pre><?php echo var_export($this->request->getParams(), true) ?></pre>
  		<?php endif ?>
  	</body>
</html>
<? else: ?>
<!DOCTYPE html>
<html lang="uk">
<head>
    <title><?php echo $this->title; ?></title>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <meta name="description" content="<?= $this->description ?>"/>
    <meta name="keywords" content="<?= $this->keywords ?>"/>

    <!--[if lte IE 8]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!--[if lt IE 8]>
    <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE8.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" type="text/css" href="/static/default/css/style.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="/static/default/css/adaptive.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="/static/default/css/fancybox.css" media="screen"/>

    <script type="text/javascript" src="/static/default/js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="/static/default/js/script.js"></script>
    <?=$this->headScript()?>
    <script>
        var inProgress = false;
        var page = 2;

        function setCurrentCityAndArea()
        {
            var city_id = '<?=$this->currentCity?$this->currentCity->getId():0?>';
            if (city_id != 0) {
                $('.city_'+city_id).attr('checked','checked');
            }
        }

        function changeArea(ele, area_url)
        {
            var httpText = 'http://';
            var site_name = '<?=SITE_NAME?>';
            var city = $(ele).data('url');

            window.location.href = httpText+city+'.'+site_name+'/'+area_url;
        }

        function changeCity(ele, clickFn)
        {
            if (clickFn) {
                var httpText = 'http://';
                var site_name = '<?=SITE_NAME?>';
                var city = ele.data('url');

                window.location.href = httpText+city+'.'+site_name;
            }
            $('#empty_area').html('– <?=Kernel_Block::getText('Сначала выберите район', $this->blocks);?> –');
            var cityId = ele.val();
            $('.area_inp').hide();
            $('.area_in_city_'+cityId).show();
        }

        function sendSubscribe(form_ele)
        {
            var url = '<?=$this->url(array(),'default-subscribe-add-ajax')?>';

            var form = $(form_ele);
            var args = {
                'city_id': '<?=$this->currentCity?$this->currentCity->getId():0?>',
                'area_id': '<?=isset($this->area)?$this->area->getId():0?>',
                'email': form.find('.input_subscribe').val()
            };

            $.post( url, args, function( data ) {
                if (typeof data.error != 'undefined') {
                    $.each( data.error, function( key, value ) {
                        alert( key + ": " + value );
                    });
                } else {
                    alert('<p><?=Kernel_Block::getText('Спасибо Вы подписаны на новости!', $this->blocks);?></p>');
                    form.find('.input_subscribe').val('');
                }
                console.log(data);
            }, "json");


            return false;
        }

        function goToPage(ele)
        {
            var httpText = 'http://';
            var site_name = '<?=SITE_NAME?>';
            var city = $('input[name=city]:checked').data('url');
            var area = $('input[name=area]:checked').data('url');
            var word = $('input[name=word]').val().trim();

            if (city != '') {
                httpText+= city+'.';
            }
            httpText += site_name;
            if (area != '' && area != null) {
                httpText+= '/'+area;
            }
            if (word != '') {
                httpText+= '/'+word;
            }

            window.location.href = httpText;

            return false;
        }

        function getAjaxPage()
        {
            if (page == 0 || inProgress)
                return false;

            inProgress = true;

            var city_id = '<?=$this->currentCity?$this->currentCity->getId():0?>';
            var area_id = '<?=isset($this->area)?$this->area->getId():0?>';
            var word = '<?=isset($this->word)?$this->word:''?>';

            $.getJSON( "<?=$this->url(array(), 'default-salons-get-ajax');?>",
                {
                    city: city_id,
                    area: area_id,
                    word: word,
                    page: page
                }
            ).done(function( data ) {
                    if (data.success) {
                        $('#list_block').append(data.html);
                        page = data.page;
                    } else {
                        console.log(data.error);
                    }
                    inProgress = false;
                });
        }
    </script>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-50440505-1', 'viprelax.net');
        ga('send', 'pageview');

    </script>
</head>
<body>
    <?php echo $this->partial('blocks/header.phtml', array (
                                                           'menu' => $this->menu,
                                                           'blocks' => $this->blocks,
                                                           'siteSetings' => $this->siteSetings,
                                                           'cityContent' => $this->currentCityContent,
                                                           'currentLang' => $this->currentLang,
                                                           'area' => isset($this->area)?$this->area:false,
                                                           'word' => isset($this->word)?$this->word:'',
                                                     )) ?>
    <section class="container">
        <div class="wrapper">
            <style>
                article p{
                    color: #fff!important;
                }
            </style>
            Страница не найдена
        </div>
    </section>
    <?php echo $this->partial('blocks/footer.phtml', array (
                                                           'blocks'      => $this->blocks,
                                                           'siteSetings' => $this->siteSetings
                                                     )) ?>
    <script>
        $(function(){
            changeCity($('#<?=$this->currentCity?$this->currentCity->getUrl():0?>'), false);
            setCurrentCityAndArea();
            $('body').on('click','.pagination a', function(){
                getAjaxPage($(this).data('page'))

                return false;
            });
        });
    </script>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter24223378 = new Ya.Metrika({id:24223378,
                        webvisor:true,
                        clickmap:true,
                        accurateTrackBounce:true});
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/24223378" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</body>
</html>
<? endif; ?>