<!DOCTYPE html>
<html lang="uk">
<head>
    <title><?php echo $this->title; ?></title>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <meta name="description" content="<?= $this->description ?>"/>
    <meta name="keywords" content="<?= $this->keywords ?>"/>

    <!--[if lte IE 8]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!--[if lt IE 8]>
    <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE8.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" type="text/css" href="/static/default/css/style.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="/static/default/css/adaptive.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="/static/default/css/fancybox.css" media="screen"/>

    <script type="text/javascript" src="/static/default/js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="/static/default/js/script.js"></script>
    <?=$this->headScript()?>
</head>
<body>
    <?php echo $this->partial('blocks/header.phtml', array ('menu' => $this->menu, 'blocks' => $this->blocks, 'siteSetings' => $this->siteSetings, 'item' => isset($this->itemContent) ? true : false)) ?>
    <section class="container">
        <div class="wrapper">
            <?php echo $this->layout()->content ?>
        </div>
    </section>
    <?php echo $this->partial('blocks/footer.phtml', array (
                                                           'blocks'      => $this->blocks,
                                                           'siteSetings' => $this->siteSetings
                                                     )) ?>
</body>
</html>