<!DOCTYPE html>
<html lang="uk">
<head>
    <title><?php echo $this->title; ?></title>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
    <meta name="description" content="<?= $this->description ?>"/>
    <meta name="keywords" content="<?= $this->keywords ?>"/>
    <?php $uriq = trim($_SERVER['REQUEST_URI']); ?>
    <?php if(strlen($uriq) > 5): ?>
        <META NAME="ROBOTS" CONTENT="NOINDEX,NOFOLLOW">
    <? endif; ?>
    <meta name='yandex-verification' content='640b7b0663c2edc7' />
    <?= $this->headText; ?>
    <!--[if lte IE 8]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!--[if lt IE 8]>
    <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE8.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" type="text/css" href="/static/default/css/style.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="/static/default/css/adaptive.css" media="screen"/>
    <link rel="stylesheet" type="text/css" href="/static/default/css/fancybox.css" media="screen"/>

    <script type="text/javascript" src="/static/default/js/jquery-1.9.1.min.js"></script>
    <script type="text/javascript" src="/static/default/js/script.js"></script>
    <?=$this->headScript()?>
    <script>
        var inProgress = false;
        var page = 2;
        var SITE_NAME = '<?=SITE_NAME?>';
        var URL_SUBSCRIBE = '<?=$this->url(array(),'default-subscribe-add-ajax')?>';
        var URL_PAGINATION = "<?=$this->url(array(), 'default-salons-get-ajax');?>";
        var CITY_ID = '<?=$this->currentCity?$this->currentCity->getId():0?>';
        var AREA_ID = '<?=isset($this->area)?$this->area->getId():0?>';
        var CURRENT_WORD = '<?=isset($this->word)?$this->word:''?>';
        var TEXT_SELECT_CITY = '– <?=Kernel_Block::getText('Сначала выберите район', $this->blocks);?> –';
        var TEXT_NEWS_SUBSCRIBE = '<p><?=Kernel_Block::getText('Спасибо Вы подписаны на новости!', $this->blocks);?></p>';
        var TEXT_AFTER_PHONE = '<?=Kernel_Block::getText('скидка 5% за упоминание сайта viprelax', $this->blocks);?>';
    </script>

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-50440505-1', 'viprelax.net');
        ga('send', 'pageview');

    </script>

</head>
<body>
    <?php echo $this->partial('blocks/header.phtml', array (
                                                           'menu' => $this->menu,
                                                           'blocks' => $this->blocks,
                                                           'siteSetings' => $this->siteSetings,
                                                           'cityContent' => $this->currentCityContent,
                                                           'currentLang' => $this->currentLang,
                                                           'area' => isset($this->area)?$this->area:false,
                                                           'word' => isset($this->word)?$this->word:'',
                                                     )) ?>
    <section class="container">
        <div class="wrapper">
            <style>
                article p{
                    color: #fff!important;
                }
            </style>
            <?php echo $this->layout()->content ?>
        </div>
    </section>
    <?php echo $this->partial('blocks/footer.phtml', array (
                                                           'blocks'      => $this->blocks,
                                                           'siteSetings' => $this->siteSetings

                                                     )) ?>
    <script type="text/javascript" src="/static/default/js/more.js"></script>
    <script>
        $(function(){
            changeCity($('#<?=$this->currentCity?$this->currentCity->getUrl():0?>'), false);
            setCurrentCityAndArea();
            $('body').on('click','.pagination a', function(){
                getAjaxPage($(this).data('page'))

                return false;
            });
        });
    </script>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter24223378 = new Ya.Metrika({id:24223378,
                        webvisor:true,
                        clickmap:true,
                        accurateTrackBounce:true});
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/24223378" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</body>
</html>
