<header>
    <div class="wrapper">
        <a class="logo" href="<?=Kernel_City::getUrlForLink(false)?>"><img src="/static/default/images/logo.png"></a>
        <div class="top-info">
            <a href="#">
                <img src="/static/default/images/content/topinfo.png" alt="">
            </a>
        </div>
        <div class="clear"></div>
        <div class="searchBox">
            <form action="">
                <div id="selectOne" class="selectBox">
                    <? if ($this->cityContent != false) :?>
                        <a href="#">– <?=$this->cityContent['contentName']->getFieldText();?> –</a>
                    <? else: ?>
                        <a href="#">– Все города –</a>
                    <? endif; ?>
                    <div class="select-option-box">
                        <?=$this->ShowListCities()?>
                    </div>
                </div>
                <div id="selectTwo" class="selectBox">
                    <? if ($this->area != false) :?>
                        <? $content = $this->area->getContent()->getFields();?>
                        <a href="#">– <?=$content['contentName']->getFieldText();?> –</a>
                    <? else: ?>
                        <a href="#" id="empty_area">– Сначала выберите город –</a>
                    <? endif; ?>
                    <div class="select-option-box">
                        <?=$this->ShowListArea($this->area)?>
                    </div>
                </div>
                <input type="text" name="" size="" value="Поиск по названию салона" onblur="if (this.value == '') {this.value = 'Поиск по названию салона';}" onfocus="if (this.value == 'Поиск по названию салона') {this.value = '';}"/>
                <div class="clear"></div>
                <input type="submit" name="" size="" value="Показать салоны" />
                <!--
                <input type="button" name="" size="" value="Показать салоны" />
                <button>Показать салоны</button>
                -->
                <div class="clear"></div>
            </form>
        </div>
    </div>
</header>