<?= $this->partial('blocks/menus/top.phtml'); ?>
<table class="zebra" id="projectsTable">
    <thead>
    <tr>
        <td style="width: 10%;"></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    </thead>
    <?php if (count($this->massages)): ?>
        <?php $class = ''; ?>
        <tbody>
        <? $i = 0; ?>
        <? foreach ($this->massages as $item): ?>
            <? $content = $item->getContent()->getFields(); ?>
            <? $i++; ?>
            <? ($class === 'grey') ? $class = '' : $class = 'grey'; ?>
            <tr id="<?= $item->getId() ?>" class="<?= $class; ?> id_<?= $item->getId() ?>">
                <td>
                    <a href="<?= $this->url(array ('id' => $item->getId(), 'salon_id'=>$this->salon_id), 'admin-girl-edit'); ?>" class="edit"
                       title="Редактировать">
                        <img src="/static/admin/images/edit.png" alt="Edit" width="16" height="16"/>
                    </a>
                </td>
                <td style="padding-left:10px;">
                    <?=$content['contentName']->getFieldText();?>
                </td>
                <td style="text-align: right;"></td>
                <td style="text-align: left;">
                </td>
                <td style="text-align: left;">
                    <a href="#" class="delete" title="Удалить"><img src="/static/admin/images/icon_delete.gif" alt=""
                                                                    width="9" height="8"/></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    <?php endif; ?>
</table>
