<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<style>
    .descText img {
        max-width: 350px;
        float: right;
        margin: 0 15px;
        padding: 5px;
        border: 1px solid #fff;
    }
</style>
<div class="singleSalonBox">
    <div class="salonContent">
        <?=$this->ShowSubscribe();?>
        <div class="descText" style="margin-top: 10px; padding: 20px;">
            <article>
                <span style="margin-bottom: 10px; display: block;">
                    <a style="color:#a7a6a6" href="<?=$this->url(array(),'default-type-massage')?>"><< Все виды массажа</a>
                </span>
                <h1><?=$this->contentPage['name']->getFieldText();?></h1>
                <img src="<?=$this->mass->getPhoto1()->getPath('350', true)?>"/>
                <?=$this->contentPage['content']->getFieldText();?>
                <p></p>
            </article>
        </div>
        <div class="clear"></div>
        <?=$this->ShowSubscribe();?>
    </div>
</div>