<? $this->headScript()->captureStart() ?>
<? $this->headScript()->captureEnd() ?>
<style>
    .descText img {
        max-width: 350px;
        float: right;
        margin: 0 15px;
        padding: 5px;
        border: 1px solid #fff;
    }
</style>
<div class="singleSalonBox">
    <div class="salonContent">
        <?=$this->ShowSubscribe();?>
        <div class="descText" style="margin-top: 10px; padding: 20px;">
            <article>
                <span style="margin-bottom: 10px; display: block;">
                    <a style="color:#a7a6a6" href="<?=$this->url(array(),'default-type-massage')?>"><< Все виды массажа</a>
                </span>
                <h1><?=$this->contentPage['name']->getFieldText();?></h1>
                <img src="<?=$this->mass->getPhoto1()->getPath('350', true)?>"/>
                <table border="0" cellpadding="5" cellspacing="5" style="font-size: 12.0120115280151px; width: 500px;">
                    <tbody>
                    <tr>
                        <td>
                            <p style="margin-left: 1.5pt; text-align: justify;">
                                <?=isset($this->contentPage['paragraf'])?$this->contentPage['paragraf']->getFieldText():'';?></p>
                        </td>
                    </tr>
                    </tbody>
                </table>
                <table border="0" cellpadding="5" cellspacing="5" style="font-size: 12.0120115280151px; width: 800px;">
                    <tbody>
                    <tr>
                        <td>
                            <p style="margin-left: 1.5pt; text-align: justify;"><?=$this->contentPage['content']->getFieldText();?></p>
                        </td>
                        <td>
                            <?=$this->siteSetings->getMassLinks();?>
                        </td>
                    </tr>
                    </tbody>
                </table>

            </article>
        </div>
        <div class="clear"></div>
        <?=$this->ShowSubscribe();?>
    </div>
</div>